- name: System | Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: System | Install python-software-properties
  apt: pkg=python-software-properties state=installed

- name: System | Install Build-Essentials
  apt: pkg=build-essential state=installed

- name: System | Install ACL
  apt: pkg=acl state=installed

- name: System | Install cURL
  apt: pkg=curl state=installed

- name: System | Install Git
  apt: pkg=git-core state=installed

- name: System | Install Ruby Development Headers
  apt: pkg=ruby2.3 state=installed

- name: System | Install Ruby Gems Package
  apt: pkg=rubygems-integration state=installed
